### ISSUE TITLE
[FEATURE] Update docs

### ISSUE THREAD

**Issue by bytex0a** [OdatNurd/SnAPI#1]
Will there be an update to the new ST4 documentation?

**Comment by OdatNurd** [comment]
There will indeed, but I don't have an ETA at the moment. The change is about 50% done but it's taking a bit more time because of all of the newer stuff, adding in new cross links in places there didn't used to be, and work on annotating entries with build versions.

**Comment by bytex0a** [comment]
Thats's great to hear. Keep it up!
